# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout.addWidget(self.textEdit_2, 1, 0, 1, 4)
        self.Button_Add = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Add.setObjectName("Button_Add")
        self.gridLayout.addWidget(self.Button_Add, 3, 0, 1, 1)
        self.Button_Substract = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Substract.setObjectName("Button_Substract")
        self.gridLayout.addWidget(self.Button_Substract, 3, 1, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 4)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 4)
        self.Button_Divide = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Divide.setObjectName("Button_Divide")
        self.gridLayout.addWidget(self.Button_Divide, 3, 3, 1, 1)
        self.Button_Multiply = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Multiply.setObjectName("Button_Multiply")
        self.gridLayout.addWidget(self.Button_Multiply, 3, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button_Add.setText(_translate("MainWindow", "Add"))
        self.Button_Substract.setText(_translate("MainWindow", "Substract"))
        self.label.setText(_translate("MainWindow", "0"))
        self.Button_Divide.setText(_translate("MainWindow", "Divide"))
        self.Button_Multiply.setText(_translate("MainWindow", "Multiply"))
